SalesforceRecruitingOnSecondOrg/src/objects/CandidateCV__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unemployed</fullName>
                </value>
                <value>
                    <fullName>Employed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CandidateCV</label>
    <nameField>
        <label>CandidateCV Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CandidatesCVs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SalesforceRecruitingOnSecondOrg/src/objects/Job_Advertisement__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Maximum_Salary__c</fullName>
        <label>Maximum Salary</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Minimum_Salary__c</fullName>
        <label>Minimum Salary</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Salary__c</fullName>
        <label>Salary</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Job Advertisement</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>JobAdvertisements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SalesforceRecruitingOnSecondOrg/src/objects/Selected_Job__c.object
<CustomObject>
    <fields>
        <fullName>CandidateCV__c</fullName>
        <label>CandidateCV</label>
        <referenceTo>CandidateCV__c</referenceTo>
        <relationshipLabel>Selected Jobs</relationshipLabel>
        <relationshipName>Selected_Jobs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Job_Advertisement__c</fullName>
        <label>Job Advertisement</label>
        <referenceTo>Job_Advertisement__c</referenceTo>
        <relationshipLabel>Selected Jobs</relationshipLabel>
        <relationshipName>Selected_Jobs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Selected Job</label>
    <nameField>
        <displayFormat>Selected_Job-{0000}</displayFormat>
        <label>Selected Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Selected Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SalesforceRecruitingOnSecondOrg/src/classes/TestDataFactory.cls
@isTest
public class TestDataFactory {
    public static List<Job_Advertisement__c> createJobAdvertisements(integer numberOfRecords, string status, Integer minSalary, Integer maxSalary){
        List<Job_Advertisement__c> listOfTestData = new List<Job_Advertisement__c>();
        for(integer i = 0; i< numberOfRecords; i++){
            Job_Advertisement__c testData = new Job_Advertisement__c();
            testData.Name = 'Test data ' + i;
            testData.Minimum_Salary__c = minSalary;
            testData.Maximum_Salary__c = maxSalary;
            testData.Status__c = status;
            if(minSalary != 0 && maxSalary != 0){
                testData.Salary__c = minSalary +'K-'+maxSalary+'K';
            }
            else if(minSalary != 0 && maxSalary == 0){
                testData.Salary__c = minSalary +'K+';
            }
            else if(minSalary == 0 && maxSalary == 0){
                testData.Salary__c = '';
            }
            listOfTestData.add(testData);
        }
        insert listOfTestData;
        return listOfTestData;
    }
    public static List<CandidateCV__c> createCandidatesCV(Integer numberOfRecords){
        List<CandidateCV__c> listOfTestData = new List<CandidateCV__c>();
        for(integer i = 0; i< numberOfRecords; i++){
            CandidateCV__c testData = new CandidateCV__c();
            testData.Name = 'Test data ' + i;
            testData.Email__c = 'testdata'+i+'@mail.com';
            listOfTestData.add(testData);
        }
        insert listOfTestData;
        return listOfTestData;
    }
    public static List<Selected_Job__c> createSelectedJob(id candidateId, id jobId, integer numberOfRecords){
        List<Selected_Job__c> listOfTestData = new List<Selected_Job__c>();
        for(integer i = 0; i< numberOfRecords; i++){
            Selected_Job__c testData = new Selected_Job__c();
            testData.CandidateCV__c = candidateId;
            testData.Job_Advertisement__c = jobId;
            listOfTestData.add(testData);
        }
        insert listOfTestData;
        return listOfTestData;
    }
}