SalesforceRecruitingOnSecondOrg/src/objects/CandidateCV__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unemployed</fullName>
                </value>
                <value>
                    <fullName>Employed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CandidateCV</label>
    <nameField>
        <label>CandidateCV Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CandidatesCVs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SalesforceRecruitingOnSecondOrg/src/objects/Job_Advertisement__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Job Advertisement</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>JobAdvertisements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SalesforceRecruitingOnSecondOrg/src/objects/Selected_Job__c.object
<CustomObject>
    <fields>
        <fullName>CandidateCV__c</fullName>
        <label>CandidateCV</label>
        <referenceTo>CandidateCV__c</referenceTo>
        <relationshipLabel>Selected Jobs</relationshipLabel>
        <relationshipName>Selected_Jobs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Job_Advertisement__c</fullName>
        <label>Job Advertisement</label>
        <referenceTo>Job_Advertisement__c</referenceTo>
        <relationshipLabel>Selected Jobs</relationshipLabel>
        <relationshipName>Selected_Jobs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Selected Job</label>
    <nameField>
        <displayFormat>Selected_Job-{0000}</displayFormat>
        <label>Selected Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Selected Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SalesforceRecruitingOnSecondOrg/src/classes/TestForDeleteSelectedJobsTrigger.cls
@isTest
public class TestForDeleteSelectedJobsTrigger {
	@isTest
    public static void deleteSelectedJobsWhenJObsIsArchivedTest(){
        CandidateCV__c testCandidate = new CandidateCV__c(Name = 'TestCV TestCandidate', Email__c = 'testcvemail@mail.com');
        insert testCandidate;
        List<Job_Advertisement__c> job = TestDataFactory.createJobAdvertisements(1, 'Active', 50, 75);
        Selected_Job__c testJob = new Selected_Job__c(CandidateCV__c = testCandidate.id, Job_Advertisement__c = job[0].id);
        insert testJob;
        Job_Advertisement__c testJobAdvertisement = [select id from Job_Advertisement__c];
        Test.startTest();
        testJobAdvertisement.Status__c = 'Archived';
        update testJobAdvertisement;
        Test.stopTest();
        List<Selected_Job__c> testSelectedJobs = [select id from Selected_Job__c];
        system.assertEquals(0, testSelectedJobs.size());
        system.assertEquals('Archived', testJobAdvertisement.Status__c);
    }
}