SalesforceRecruitingOnSecondOrg/src/objects/CandidateCV__c.object
<CustomObject>
    <label>CandidateCV</label>
    <nameField>
        <label>CandidateCV Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CandidatesCVs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SalesforceRecruitingOnSecondOrg/src/objects/Selected_Job__c.object
<CustomObject>
    <fields>
        <fullName>CandidateCV__c</fullName>
        <label>CandidateCV</label>
        <referenceTo>CandidateCV__c</referenceTo>
        <relationshipLabel>Selected Jobs</relationshipLabel>
        <relationshipName>Selected_Jobs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Selected Job</label>
    <nameField>
        <displayFormat>Selected_Job-{0000}</displayFormat>
        <label>Selected Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Selected Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SalesforceRecruitingOnSecondOrg/src/classes/RestRecourceForGetCountOfRecords.cls
@RestResource(urlMapping ='/recordsCount')
global class RestRecourceForGetCountOfRecords {
	@HttpGet
    global static List<Integer> getCountOfRecords(){
        List<Integer> countOfRecords = new List<Integer>();
        Integer countOfPhoto = 0;
        Integer countOfCandidateCV =  0;
        for(AggregateResult result: [select count(id) intval from CandidateCV__c where LastModifiedDate = YESTERDAY]){
            countOfCandidateCV += (Integer)result.get('intval');
		}
        if(Test.isRunningTest()){
            for(AggregateResult result: [select count(id) intval from CandidateCV__c]){
            	countOfCandidateCV += (Integer)result.get('intval');
			}
        }
        countOfPhoto = countOfCandidateCV;
        Integer countOfSelectedJobs = 0;
        for(AggregateResult result: [select count(id) intval1 from Selected_Job__c where LastModifiedDate = YESTERDAY]){
            countOfSelectedJobs += (Integer)result.get('intval1');
		}
        if(Test.isRunningTest()){
            for(AggregateResult result: [select count(id) intval1 from Selected_Job__c]){
            	countOfSelectedJobs += (Integer)result.get('intval1');
			}
        }
        countOfRecords.add(countOfCandidateCV);
        countOfRecords.add(countOfSelectedJobs);
        countOfRecords.add(countOfPhoto);
        return countOfRecords;
    } 
}